apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app
  labels:
    app: booking-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          env:

            - name: FRONTEND_URL
              value: "http://localhost:8081"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://booking-app-postgresql.default.svc.cluster.local:5432/booking_db"

            - name: SPRING_PROFILES_ACTIVE
              value: dev

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: booking-app-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-app-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: booking-app-secret
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: booking-app-secret
                  key: STRIPE_SECRET_KEY

            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: booking-app-secret
                  key: STRIPE_WEBHOOK_SECRET
