name: deploy application

description: This deploys the java application on k8s cluster

inputs:
  eks-cluster-name:
    description: name of eks cluster
    required: true
  DB_PASSWORD:
    description: database password
    required: true
  DB_USERNAME:
    description: database username
    required: true
  JWT_SECRET:
    description: jwt secret
    required: true
  STRIPE_SECRET_KEY:
    description: stripe key
    required: true
  STRIPE_WEBHOOK_SECRET:
    description: webhook secret
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::471208935946:role/Githubactions
        aws-region: eu-central-1

    - name: setup k8s context
      if: success()
      run: |
        aws eks --region eu-central-1 update-kubeconfig --name ${{inputs.eks-cluster-name}}
      shell: bash


    - name: kubernetes create secret
      if: success()
      run: |
        kubectl create secret generic booking-app-secret \
           --from-literal=DB_PASSWORD="${{ inputs.DB_PASSWORD }}"  \
           --from-literal=DB_USERNAME="${{ inputs.DB_USERNAME }}" \
           --from-literal=JWT_SECRET="${{ inputs.JWT_SECRET }}" \
           --from-literal=STRIPE_SECRET_KEY="${{ inputs.STRIPE_SECRET_KEY }}" \
           --from-literal=STRIPE_WEBHOOK_SECRET="${{ inputs.STRIPE_WEBHOOK_SECRET }}"
      shell: bash

    - name: helm install
      if: success()
      run: |
        helm upgrade -i booking-app .
      shell: bash

    - name: install aws load balancer controller
      if: success()
      run: |
        helm install aws-load-balancer-controller eks/aws-load-balancer-controller \
        -n kube-system \
        --set clusterName=booking-app-eks-cluster \
        --set serviceAccount.create=false \
        --set serviceAccount.name=aws-load-balancer-controller
      shell: bash



