name: Terraform Deploy

on:
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471208935946:role/Githubactions
          aws-region: eu-central-1


      - name: Run AWS CLI command
        run: aws s3 ls

#      - name: Terraform Init
#        run: terraform init -reconfigure
#
#      - name: Terraform Plan
#        run: terraform plan
#
#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main'
#        run: terraform apply -auto-approve
