name: Infra setup


on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471208935946:role/Githubactions
          aws-region: eu-central-1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup infrastructure
        if: success()
        uses: ./.github/actions/terraform
        with:
          working-directory: terraform

