name: Initial tf state setup

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::471208935946:role/Githubactions
          aws-region: eu-central-1


      - name: Run AWS initial bucket setup
        run: |
          aws s3api create-bucket \
          --bucket tf-state-bucket-112233 \
          --region eu-central-1 \
          --create-bucket-configuration LocationConstraint=eu-central-1 
          
          aws s3api put-bucket-versioning \
            --bucket tf-state-bucket-112233 \
            --versioning-configuration Status=Enabled


          aws dynamodb create-table \
            --table-name terraform-locks \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST \
            --region eu-central-1
        shell: bash